"""operations and backup records

Revision ID: 223071f217fe
Revises: 8a83384b8492
Create Date: 2026-07-13 16:32:57.233096
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '223071f217fe'
down_revision: Union[str, Sequence[str], None] = '8a83384b8492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.BigInteger(), nullable=False),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_runs_status'), 'backup_runs', ['status'], unique=False)
    op.create_table('operation_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('resolved_at', sa.BigInteger(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_alerts_active'), 'operation_alerts', ['active'], unique=False)
    op.create_index(op.f('ix_operation_alerts_code'), 'operation_alerts', ['code'], unique=False)
    op.create_index(op.f('ix_operation_alerts_severity'), 'operation_alerts', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_alerts_severity'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_code'), table_name='operation_alerts')
    op.drop_index(op.f('ix_operation_alerts_active'), table_name='operation_alerts')
    op.drop_table('operation_alerts')
    op.drop_index(op.f('ix_backup_runs_status'), table_name='backup_runs')
    op.drop_table('backup_runs')
    # ### end Alembic commands ###
