"""production baseline

Revision ID: 8a83384b8492
Revises:
Create Date: 2026-07-13 16:13:16.646175
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8a83384b8492'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _upgrade_legacy_database() -> None:
    """Adopt the pre-Alembic production database without recreating it.

    Haven originally created tables through SQLAlchemy at API startup. The
    first Alembic rollout must therefore fill only the schema additions that
    are absent. Later revisions can then retire the old collector tables in a
    normal, recorded migration.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # These tables belong to this baseline. The operations/backup tables are
    # intentionally left for revision 223071f217fe.
    from database.models import Base
    baseline_tables = (
        "ai_daily_usage", "candle_coverage", "cmc_assets", "market_candles",
        "provider_status", "provider_usage", "strategy_versions",
    )
    missing = [Base.metadata.tables[name] for name in baseline_tables
               if not inspector.has_table(name)]
    if missing:
        Base.metadata.create_all(bind=bind, tables=missing)

    def columns(table: str) -> set[str]:
        return {column["name"] for column in sa.inspect(bind).get_columns(table)}

    if "scopes" not in columns("api_keys"):
        op.add_column("api_keys", sa.Column(
            "scopes", sa.String(), nullable=False,
            server_default="engine:read,engine:trade,engine:report"))
        op.alter_column("api_keys", "scopes", server_default=None)
    if "expires_at" not in columns("api_keys"):
        op.add_column("api_keys", sa.Column("expires_at", sa.BigInteger(), nullable=True))

    if "code_version" not in columns("strategies"):
        op.add_column("strategies", sa.Column(
            "code_version", sa.Integer(), nullable=False, server_default="1"))
        op.alter_column("strategies", "code_version", server_default=None)
    if "live_approved_version" not in columns("strategies"):
        op.add_column("strategies", sa.Column(
            "live_approved_version", sa.Integer(), nullable=True))

    trade_columns = columns("trade_history")
    additions = (
        sa.Column("chain_id", sa.String(), nullable=True),
        sa.Column("submitted_at", sa.BigInteger(), nullable=True),
        sa.Column("confirmed_at", sa.BigInteger(), nullable=True),
        sa.Column("block_number", sa.BigInteger(), nullable=True),
        sa.Column("reconciliation_state", sa.String(), nullable=True),
        sa.Column("receipt_json", sa.Text(), nullable=True),
        sa.Column("intent_hash", sa.String(), nullable=True),
    )
    for column in additions:
        if column.name not in trade_columns:
            op.add_column("trade_history", column)
    indexes = {index["name"] for index in sa.inspect(bind).get_indexes("trade_history")}
    if "ix_trade_history_intent_hash" not in indexes:
        op.create_index("ix_trade_history_intent_hash", "trade_history", ["intent_hash"])


def upgrade() -> None:
    # A legacy Haven database already has api_keys but no Alembic revision.
    # Adopt it in place; a genuinely empty database follows the full baseline.
    if sa.inspect(op.get_bind()).has_table("api_keys"):
        _upgrade_legacy_database()
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_daily_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('usage_date', sa.String(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_ai_daily_user')
    )
    op.create_index(op.f('ix_ai_daily_usage_usage_date'), 'ai_daily_usage', ['usage_date'], unique=False)
    op.create_index(op.f('ix_ai_daily_usage_user_id'), 'ai_daily_usage', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_used_at', sa.BigInteger(), nullable=True),
    sa.Column('revoked', sa.Integer(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('candle_coverage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cmc_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('start_time', sa.BigInteger(), nullable=False),
    sa.Column('end_time', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cmc_id', 'platform', 'contract_address', 'interval', name='uq_candle_coverage_identity')
    )
    op.create_index(op.f('ix_candle_coverage_cmc_id'), 'candle_coverage', ['cmc_id'], unique=False)
    op.create_table('chart_markers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('marker_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('user_placed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('triggered_at', sa.BigInteger(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_markers_symbol'), 'chart_markers', ['symbol'], unique=False)
    op.create_index(op.f('ix_chart_markers_user_id'), 'chart_markers', ['user_id'], unique=False)
    op.create_table('cmc_assets',
    sa.Column('cmc_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('cmc_id')
    )
    op.create_index(op.f('ix_cmc_assets_contract_address'), 'cmc_assets', ['contract_address'], unique=False)
    op.create_index(op.f('ix_cmc_assets_expires_at'), 'cmc_assets', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cmc_assets_platform'), 'cmc_assets', ['platform'], unique=False)
    op.create_index(op.f('ix_cmc_assets_rank'), 'cmc_assets', ['rank'], unique=False)
    op.create_index(op.f('ix_cmc_assets_slug'), 'cmc_assets', ['slug'], unique=False)
    op.create_index(op.f('ix_cmc_assets_symbol'), 'cmc_assets', ['symbol'], unique=False)
    op.create_table('daily_buckets',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('bucket_start', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('buy_volume', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'bucket_start')
    )
    op.create_index(op.f('ix_daily_buckets_bucket_start'), 'daily_buckets', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_daily_buckets_symbol'), 'daily_buckets', ['symbol'], unique=False)
    op.create_table('debug_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debug_logs_level'), 'debug_logs', ['level'], unique=False)
    op.create_index(op.f('ix_debug_logs_source'), 'debug_logs', ['source'], unique=False)
    op.create_index(op.f('ix_debug_logs_timestamp'), 'debug_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_debug_logs_user_id'), 'debug_logs', ['user_id'], unique=False)
    op.create_table('engine_settings',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'key')
    )
    op.create_table('fifteen_min_buckets',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('bucket_start', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('buy_volume', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'bucket_start')
    )
    op.create_index(op.f('ix_fifteen_min_buckets_bucket_start'), 'fifteen_min_buckets', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_fifteen_min_buckets_symbol'), 'fifteen_min_buckets', ['symbol'], unique=False)
    op.create_table('finders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('params_json', sa.String(), nullable=True),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('last_run_at', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finders_user_id'), 'finders', ['user_id'], unique=False)
    op.create_table('heartbeats',
    sa.Column('process', sa.String(), nullable=False),
    sa.Column('last_heartbeat', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('process')
    )
    op.create_index(op.f('ix_heartbeats_process'), 'heartbeats', ['process'], unique=False)
    op.create_table('latest_tickers',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price_change_24h', sa.Float(), nullable=True),
    sa.Column('volume_24h', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_latest_tickers_symbol'), 'latest_tickers', ['symbol'], unique=False)
    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cmc_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('trader_count', sa.Integer(), nullable=True),
    sa.Column('closed', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cmc_id', 'platform', 'contract_address', 'interval', 'open_time', name='uq_market_candle_identity')
    )
    op.create_index(op.f('ix_market_candles_closed'), 'market_candles', ['closed'], unique=False)
    op.create_index(op.f('ix_market_candles_cmc_id'), 'market_candles', ['cmc_id'], unique=False)
    op.create_index(op.f('ix_market_candles_contract_address'), 'market_candles', ['contract_address'], unique=False)
    op.create_index(op.f('ix_market_candles_interval'), 'market_candles', ['interval'], unique=False)
    op.create_index(op.f('ix_market_candles_open_time'), 'market_candles', ['open_time'], unique=False)
    op.create_index(op.f('ix_market_candles_platform'), 'market_candles', ['platform'], unique=False)
    op.create_table('one_min_buckets',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('bucket_start', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('buy_volume', sa.Float(), nullable=True),
    sa.Column('sell_volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'bucket_start')
    )
    op.create_index(op.f('ix_one_min_buckets_bucket_start'), 'one_min_buckets', ['bucket_start'], unique=False)
    op.create_index(op.f('ix_one_min_buckets_symbol'), 'one_min_buckets', ['symbol'], unique=False)
    op.create_table('pools',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('dex', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('token_id', sa.String(), nullable=True),
    sa.Column('quote_address', sa.String(), nullable=True),
    sa.Column('token_is_token0', sa.Integer(), nullable=True),
    sa.Column('fee_tier', sa.Integer(), nullable=True),
    sa.Column('liquidity_usd', sa.Float(), nullable=True),
    sa.Column('watch', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('last_checked', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_chain'), 'pools', ['chain'], unique=False)
    op.create_index(op.f('ix_pools_token_id'), 'pools', ['token_id'], unique=False)
    op.create_index(op.f('ix_pools_watch'), 'pools', ['watch'], unique=False)
    op.create_table('provider_status',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('last_event_at', sa.BigInteger(), nullable=True),
    sa.Column('last_reconciled_at', sa.BigInteger(), nullable=True),
    sa.Column('reconnect_count', sa.Integer(), nullable=True),
    sa.Column('gap_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('provider')
    )
    op.create_table('provider_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('captured_at', sa.BigInteger(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=True),
    sa.Column('credits_left', sa.Integer(), nullable=True),
    sa.Column('requests_left_minute', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_usage_captured_at'), 'provider_usage', ['captured_at'], unique=False)
    op.create_index(op.f('ix_provider_usage_provider'), 'provider_usage', ['provider'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('params_json', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('finder_id', sa.String(), nullable=True),
    sa.Column('max_positions', sa.Integer(), nullable=True),
    sa.Column('switch_margin_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.Column('last_run_at', sa.BigInteger(), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('code_version', sa.Integer(), nullable=False),
    sa.Column('live_approved_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_user_id'), 'strategies', ['user_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('approved_for_live', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_strategy_version')
    )
    op.create_index(op.f('ix_strategy_versions_strategy_id'), 'strategy_versions', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_versions_user_id'), 'strategy_versions', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('price_id', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.BigInteger(), nullable=True),
    sa.Column('early', sa.Integer(), nullable=True),
    sa.Column('extra_bots', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_table('tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('chain_id', sa.String(), nullable=True),
    sa.Column('contract_address', sa.String(), nullable=True),
    sa.Column('display_symbol', sa.String(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('liquidity_usd', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('cmc_rank', sa.Integer(), nullable=True),
    sa.Column('cmc_slug', sa.String(), nullable=True),
    sa.Column('cmc_id', sa.Integer(), nullable=True),
    sa.Column('listed_at', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('security_json', sa.String(), nullable=True),
    sa.Column('primary_pool', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_symbol'), 'tokens', ['symbol'], unique=False)
    op.create_table('trade_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('marker_id', sa.String(), nullable=True),
    sa.Column('expected_price', sa.Float(), nullable=True),
    sa.Column('execution_price', sa.Float(), nullable=True),
    sa.Column('amount_in', sa.Float(), nullable=True),
    sa.Column('amount_out', sa.Float(), nullable=True),
    sa.Column('fee_token', sa.String(), nullable=True),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('gas_used', sa.BigInteger(), nullable=True),
    sa.Column('gas_price_gwei', sa.Float(), nullable=True),
    sa.Column('gas_cost_native', sa.Float(), nullable=True),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('block_time', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('chain_id', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.BigInteger(), nullable=True),
    sa.Column('confirmed_at', sa.BigInteger(), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('reconciliation_state', sa.String(), nullable=True),
    sa.Column('receipt_json', sa.Text(), nullable=True),
    sa.Column('intent_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    op.create_index(op.f('ix_trade_history_intent_hash'), 'trade_history', ['intent_hash'], unique=False)
    op.create_index(op.f('ix_trade_history_symbol'), 'trade_history', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_history_user_id'), 'trade_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_history_user_id'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_symbol'), table_name='trade_history')
    op.drop_index(op.f('ix_trade_history_intent_hash'), table_name='trade_history')
    op.drop_table('trade_history')
    op.drop_index(op.f('ix_tokens_symbol'), table_name='tokens')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_strategy_versions_user_id'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_strategy_id'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_strategies_user_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_provider_usage_provider'), table_name='provider_usage')
    op.drop_index(op.f('ix_provider_usage_captured_at'), table_name='provider_usage')
    op.drop_table('provider_usage')
    op.drop_table('provider_status')
    op.drop_index(op.f('ix_pools_watch'), table_name='pools')
    op.drop_index(op.f('ix_pools_token_id'), table_name='pools')
    op.drop_index(op.f('ix_pools_chain'), table_name='pools')
    op.drop_table('pools')
    op.drop_index(op.f('ix_one_min_buckets_symbol'), table_name='one_min_buckets')
    op.drop_index(op.f('ix_one_min_buckets_bucket_start'), table_name='one_min_buckets')
    op.drop_table('one_min_buckets')
    op.drop_index(op.f('ix_market_candles_platform'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_open_time'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_interval'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_contract_address'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_cmc_id'), table_name='market_candles')
    op.drop_index(op.f('ix_market_candles_closed'), table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index(op.f('ix_latest_tickers_symbol'), table_name='latest_tickers')
    op.drop_table('latest_tickers')
    op.drop_index(op.f('ix_heartbeats_process'), table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_index(op.f('ix_finders_user_id'), table_name='finders')
    op.drop_table('finders')
    op.drop_index(op.f('ix_fifteen_min_buckets_symbol'), table_name='fifteen_min_buckets')
    op.drop_index(op.f('ix_fifteen_min_buckets_bucket_start'), table_name='fifteen_min_buckets')
    op.drop_table('fifteen_min_buckets')
    op.drop_table('engine_settings')
    op.drop_index(op.f('ix_debug_logs_user_id'), table_name='debug_logs')
    op.drop_index(op.f('ix_debug_logs_timestamp'), table_name='debug_logs')
    op.drop_index(op.f('ix_debug_logs_source'), table_name='debug_logs')
    op.drop_index(op.f('ix_debug_logs_level'), table_name='debug_logs')
    op.drop_table('debug_logs')
    op.drop_index(op.f('ix_daily_buckets_symbol'), table_name='daily_buckets')
    op.drop_index(op.f('ix_daily_buckets_bucket_start'), table_name='daily_buckets')
    op.drop_table('daily_buckets')
    op.drop_index(op.f('ix_cmc_assets_symbol'), table_name='cmc_assets')
    op.drop_index(op.f('ix_cmc_assets_slug'), table_name='cmc_assets')
    op.drop_index(op.f('ix_cmc_assets_rank'), table_name='cmc_assets')
    op.drop_index(op.f('ix_cmc_assets_platform'), table_name='cmc_assets')
    op.drop_index(op.f('ix_cmc_assets_expires_at'), table_name='cmc_assets')
    op.drop_index(op.f('ix_cmc_assets_contract_address'), table_name='cmc_assets')
    op.drop_table('cmc_assets')
    op.drop_index(op.f('ix_chart_markers_user_id'), table_name='chart_markers')
    op.drop_index(op.f('ix_chart_markers_symbol'), table_name='chart_markers')
    op.drop_table('chart_markers')
    op.drop_index(op.f('ix_candle_coverage_cmc_id'), table_name='candle_coverage')
    op.drop_table('candle_coverage')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ai_daily_usage_user_id'), table_name='ai_daily_usage')
    op.drop_index(op.f('ix_ai_daily_usage_usage_date'), table_name='ai_daily_usage')
    op.drop_table('ai_daily_usage')
    # ### end Alembic commands ###
