"""retire legacy collectors and billing fields

Revision ID: a52ee57a1071
Revises: 223071f217fe
Create Date: 2026-07-13 16:43:06.770499
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a52ee57a1071'
down_revision: Union[str, Sequence[str], None] = '223071f217fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_one_min_buckets_bucket_start'), table_name='one_min_buckets')
    op.drop_index(op.f('ix_one_min_buckets_symbol'), table_name='one_min_buckets')
    op.drop_table('one_min_buckets')
    op.drop_index(op.f('ix_daily_buckets_bucket_start'), table_name='daily_buckets')
    op.drop_index(op.f('ix_daily_buckets_symbol'), table_name='daily_buckets')
    op.drop_table('daily_buckets')
    op.drop_index(op.f('ix_fifteen_min_buckets_bucket_start'), table_name='fifteen_min_buckets')
    op.drop_index(op.f('ix_fifteen_min_buckets_symbol'), table_name='fifteen_min_buckets')
    op.drop_table('fifteen_min_buckets')
    op.drop_index(op.f('ix_pools_chain'), table_name='pools')
    op.drop_index(op.f('ix_pools_token_id'), table_name='pools')
    op.drop_index(op.f('ix_pools_watch'), table_name='pools')
    op.drop_table('pools')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_column('subscriptions', 'early')
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'stripe_customer_id')
    op.drop_column('subscriptions', 'price_id')
    op.drop_column('tokens', 'total_supply')
    op.drop_column('tokens', 'primary_pool')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('primary_pool', sa.VARCHAR(), nullable=True))
    op.add_column('tokens', sa.Column('total_supply', sa.FLOAT(), nullable=True))
    op.add_column('subscriptions', sa.Column('price_id', sa.VARCHAR(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.VARCHAR(), nullable=True))
    op.add_column('subscriptions', sa.Column('early', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_table('pools',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('chain', sa.VARCHAR(), nullable=False),
    sa.Column('dex', sa.VARCHAR(), nullable=True),
    sa.Column('kind', sa.VARCHAR(), nullable=True),
    sa.Column('token_id', sa.VARCHAR(), nullable=True),
    sa.Column('quote_address', sa.VARCHAR(), nullable=True),
    sa.Column('token_is_token0', sa.INTEGER(), nullable=True),
    sa.Column('fee_tier', sa.INTEGER(), nullable=True),
    sa.Column('liquidity_usd', sa.FLOAT(), nullable=True),
    sa.Column('watch', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.BIGINT(), nullable=True),
    sa.Column('last_checked', sa.BIGINT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pools_watch'), 'pools', ['watch'], unique=False)
    op.create_index(op.f('ix_pools_token_id'), 'pools', ['token_id'], unique=False)
    op.create_index(op.f('ix_pools_chain'), 'pools', ['chain'], unique=False)
    op.create_table('fifteen_min_buckets',
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('bucket_start', sa.BIGINT(), nullable=False),
    sa.Column('open_price', sa.FLOAT(), nullable=True),
    sa.Column('high_price', sa.FLOAT(), nullable=True),
    sa.Column('low_price', sa.FLOAT(), nullable=True),
    sa.Column('close_price', sa.FLOAT(), nullable=True),
    sa.Column('buy_volume', sa.FLOAT(), nullable=True),
    sa.Column('sell_volume', sa.FLOAT(), nullable=True),
    sa.Column('trade_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'bucket_start')
    )
    op.create_index(op.f('ix_fifteen_min_buckets_symbol'), 'fifteen_min_buckets', ['symbol'], unique=False)
    op.create_index(op.f('ix_fifteen_min_buckets_bucket_start'), 'fifteen_min_buckets', ['bucket_start'], unique=False)
    op.create_table('daily_buckets',
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('bucket_start', sa.BIGINT(), nullable=False),
    sa.Column('open_price', sa.FLOAT(), nullable=True),
    sa.Column('high_price', sa.FLOAT(), nullable=True),
    sa.Column('low_price', sa.FLOAT(), nullable=True),
    sa.Column('close_price', sa.FLOAT(), nullable=True),
    sa.Column('buy_volume', sa.FLOAT(), nullable=True),
    sa.Column('sell_volume', sa.FLOAT(), nullable=True),
    sa.Column('trade_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'bucket_start')
    )
    op.create_index(op.f('ix_daily_buckets_symbol'), 'daily_buckets', ['symbol'], unique=False)
    op.create_index(op.f('ix_daily_buckets_bucket_start'), 'daily_buckets', ['bucket_start'], unique=False)
    op.create_table('one_min_buckets',
    sa.Column('symbol', sa.VARCHAR(), nullable=False),
    sa.Column('bucket_start', sa.BIGINT(), nullable=False),
    sa.Column('open_price', sa.FLOAT(), nullable=True),
    sa.Column('high_price', sa.FLOAT(), nullable=True),
    sa.Column('low_price', sa.FLOAT(), nullable=True),
    sa.Column('close_price', sa.FLOAT(), nullable=True),
    sa.Column('buy_volume', sa.FLOAT(), nullable=True),
    sa.Column('sell_volume', sa.FLOAT(), nullable=True),
    sa.Column('trade_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('symbol', 'bucket_start')
    )
    op.create_index(op.f('ix_one_min_buckets_symbol'), 'one_min_buckets', ['symbol'], unique=False)
    op.create_index(op.f('ix_one_min_buckets_bucket_start'), 'one_min_buckets', ['bucket_start'], unique=False)
    # ### end Alembic commands ###
