// Haven Engine — first-run setup wizard.
//
// Plain, friendly CLI that writes marker-engine/.env from two answers:
//   1) the connection key copied from the Haven website (Settings → Connect
//      your engine),
//   2) the trading wallet's private key.
//
// The private key is written ONLY to the local .env on this machine and is
// never sent to Haven's servers — the engine signs transactions locally and
// the server only ever sees the resulting on-chain trades. Re-running this
// wizard overwrites the .env (it reads existing values as defaults).
import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.join(__dirname, '.env');
const DEFAULT_API = 'https://api.haven.trade';   // overwritten by DEPLOY.md value

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q, def) => new Promise((res) => {
  rl.question(def ? `${q} [${def}]: ` : `${q}: `, (a) => res((a || '').trim() || def || ''));
});

function readExisting() {
  const out = {};
  try {
    for (const line of fs.readFileSync(ENV_PATH, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z_]+)\s*=\s*(.*)\s*$/);
      if (m) out[m[1]] = m[2];
    }
  } catch { /* first run */ }
  return out;
}

function isLikelyPk(v) {
  const s = v.startsWith('0x') ? v.slice(2) : v;
  return /^[0-9a-fA-F]{64}$/.test(s);
}

async function main() {
  console.log('\n=============================================');
  console.log('  Haven Engine — setup');
  console.log('=============================================');
  console.log('This connects your computer to your Haven account so your');
  console.log('live strategies and markers can trade. Two things are needed.\n');

  const cur = readExisting();

  const apiUrl = await ask(
    '1) Haven API address (press Enter for the default)',
    cur.HAVEN_API_URL || DEFAULT_API);

  console.log('\n   Your connection key is on the Haven website:');
  console.log('   Settings → "Connect your engine" → Generate key.\n');
  let apiKey = '';
  while (!apiKey) {
    apiKey = await ask('2) Paste your connection key', cur.HAVEN_API_KEY || '');
    if (!apiKey) console.log('   A connection key is required.');
  }

  console.log('\n   Your wallet private key stays on THIS computer only —');
  console.log('   Haven never receives it and cannot recover it if lost.');
  console.log('   Use a dedicated trading wallet holding only what you trade.\n');
  let pk = '';
  while (!pk) {
    pk = await ask('3) Paste your wallet private key', cur.PRIVATE_KEY || '');
    if (!pk) { console.log('   A private key is required to trade.'); continue; }
    if (!isLikelyPk(pk)) {
      const ok = await ask('   That does not look like a 64-char key. Use it anyway? (y/N)', 'N');
      if (!/^y/i.test(ok)) pk = '';
    }
  }

  const lines = [
    '# Haven Engine configuration — generated by setup.js',
    '# This file stays on your computer. Keep a backup of PRIVATE_KEY somewhere safe.',
    `HAVEN_API_URL=${apiUrl}`,
    `HAVEN_API_KEY=${apiKey}`,
    `PRIVATE_KEY=${pk}`,
    '',
  ];
  fs.writeFileSync(ENV_PATH, lines.join('\n'), { mode: 0o600 });
  console.log(`\n✔ Saved to ${ENV_PATH}`);
  console.log('  Start the engine with:  npm start   (or run.bat)\n');
  rl.close();
}

main().catch((e) => { console.error('Setup failed:', e.message); process.exit(1); });
